# Settings for the app
app:
  # HTML Title
  title: Virginia-Highland Master Plan
  # Header name
  name: Virginia-Highland Master Plan
  # Meta description that will show up in Google search results
  meta_description: _(Use the map to record and share the things you love about Virginia-Highland and the things you want to see changed or fixed in Virginia-Highland.)

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 33.782387
      lng: -84.354342
    zoom: 17
    minZoom: 15
    maxZoom: 17
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/openplans.map-3piqzgdc/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  love:
    label: _(Things I love)
    rules:
      - condition: '"{{location_type}}" === "love"'
        icon:
          iconUrl: /static/css/images/markers/dot-e1264d.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-e1264d.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  hate:
    label: _(Things I hate)
    rules:
      - condition: '"{{location_type}}" === "hate"'
        icon:
          iconUrl: /static/css/images/markers/dot-2654d2.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-2654d2.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  solve:
    label: _(Problems to solve)
    rules:
      - condition: '"{{location_type}}" === "solve"'
        icon:
          iconUrl: /static/css/images/markers/dot-dbcf2c.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-dbcf2c.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  preserve:
    label: _(Assets to preserve)
    rules:
      - condition: '"{{location_type}}" === "preserve"'
        icon:
          iconUrl: /static/css/images/markers/dot-70d52c.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-70d52c.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]
  idea:
    label: _(An idea I have)
    rules:
      - condition: '"{{location_type}}" === "idea"'
        icon:
          iconUrl: /static/css/images/markers/dot-744edc.png
          iconSize: [17, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-744edc.png
          shadowUrl: /static/css/images/marker-shadow.png
          iconSize: [25, 41]
          shadowSize: [41, 41]
          iconAnchor: [12, 41]

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Share what you know)
  action_text: _(added)
  title: _(Tell us more...)
  action_text: _(identified)
  anonymous_name: _(Someone)
  submit_button_label: _(Share)
  items:
    - prompt: _(What's your comment?)
      type: select
      options:
        - label: _(Something I love)
          value: love
        - label: _(Something I hate)
          value: hate
        - label: _(A problem to solve)
          value: solve
        - label: _(An asset to preserve)
          value: preserve
        - label: _(An idea I have!)
          value: idea
      name: location_type
    - prompt: _(Where is it?)
      type: text
      name: name
      attrs:
        - key: size
          value: 30
        - key: required
          value: true
    - prompt: _(What is it you like or dislike?)
      type: textarea
      name: description
      attrs:
        - key: required
          value: true
    - prompt: _(What's your idea or suggestion?)
      type: textarea
      name: idea
      attrs:
        - key: required
          value: true
    - prompt: _(Your full name)
      type: text
      name: submitter_name
      optional: false
      attrs:
        - key: size
          value: 30
        - key: required
          value: true
    - prompt: _(Your address (will not be shown on the map))
      type: text
      name: private-submitter_address
      optional: false
      attrs:
        - key: size
          value: 30
        - key: required
          value: true
    - prompt: _(Your email (will not be shown on the map))
      type: text
      name: private-submitter_email
      attrs:
        - key: size
          value: 30
survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support This!)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(How to use)
    slug: about
    name: overview
    start_page: true
