# Settings for the app
app:
  # HTML Title
  title: Virginia-Highland Master Plan 
  # Header name
  name: Virginia-Highland Master Plan 
  # Meta description that will show up in Google search results
  meta_description: _(Use the map to record and share the things you love about Virginia-Highland and the things you want to see changed or fixed in Virginia-Highland.)

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 33.782387
      lng: -84.354342
    zoom: 15
    minZoom: 14
    maxZoom: 17
  base_layer:
    url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  love:
    default: blue
    focused: red
    label: _(Things I love)
  hate:
    default: blue
    focused: red
    label: _(Things I hate)
  solve:
    default: blue
    focused: red
    label: _(Problems to solve)
  preserve:
    default: blue
    focused: red
    label: _(Assets to preserve)
  idea:
    default: blue
    focused: red
    label: _(An idea I have)
# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  blue:
    iconUrl: /static/css/images/feature-point.png
    iconSize:
      width: 17
      height: 18
    iconAnchor:
      x: 9
      y: 9
  red:
    iconUrl: /static/css/images/marker-focused.png
    shadowUrl: /static/css/images/marker-shadow.png
    iconSize:
      width: 25
      height: 41
    shadowSize:
      width: 41
      height: 41
    iconAnchor:
      x: 12
      y: 41


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Share what you know)
  action_text: _(added)
  title: _(Tell us more...)
  action_text: _(identified)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)
  items:
    - prompt: _(What's your comment?)
      type: select
      options:
        - label: _(Something I love)
          value: love
        - label: _(Something I hate)
          value: hate
        - label: _(A problem to solve)
          value: solve
        - label: _(An asset to preserve)
          value: preserve
        - label: _(An idea I have!)
          value: idea
      name: location_type
    - prompt: _(Where is it?)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Location Name)
        - key: size
          value: 30
    - prompt: _(What is it you like or dislike?)
      type: textarea
      name: description
      attrs:
        - key: placeholder
          value: _(Description...)
    - prompt: _(What's your idea or suggestion?)
      type: textarea
      name: description
      attrs:
        - key: placeholder
          value: _(Your idea/suggestion)
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Your email (will not be shown on the map))
      type: text
      name: private-submitter_email
      optional: true
      attrs:
        - key: placeholder
          value: _(Your email)
        - key: size
          value: 30
    - prompt: _(Your address (will not be shown on the map))
      type: text
      name: private-submitter_address
      optional: true
      attrs:
        - key: placeholder
          value: _(Your address)
        - key: size
          value: 30
survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support This!)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true